export const backup = [
  {
    name: "UNIVGRAD",
    initialDenaturation: "96°C, 10 min",
    denaturation: "94 °C, 30 s",
    annealing: "45-52 °C, 30 s",
    extension: "72 °C, 1 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4°C for ever",
    pcrProductSize: "",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "CYTCO45",
    initialDenaturation: "",
    denaturation: "",
    annealing: "45 °C",
    extension: "",
    numberCycles: "40 x",
    finalExtension: "",
    end: "",
    pcrProductSize: "CytB (400 bp)",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "CO1-46",
    initialDenaturation: "",
    denaturation: "",
    annealing: "46 °C",
    extension: "",
    numberCycles: "40 x",
    finalExtension: "",
    end: "",
    pcrProductSize: "COI (700 bp)",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "16S-50",
    initialDenaturation: "",
    denaturation: "",
    annealing: "50 °C",
    extension: "",
    numberCycles: "40 x",
    finalExtension: "",
    end: "",
    pcrProductSize: "16S (400 bp)",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "ITS-52",
    initialDenaturation: "",
    denaturation: "",
    annealing: "52 °C",
    extension: "",
    numberCycles: "40 x",
    finalExtension: "",
    end: "",
    pcrProductSize: "ITS1 (700 nt), ITS2 (900 nt)",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "ELAV",
    initialDenaturation: "96°C, 10 min",
    denaturation: "94 °C, 30 s",
    annealing: "50 °C",
    extension: "72 °C, 1 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4°C for ever",
    pcrProductSize: "",
    note: "sometimes: 54 °C 10x, then 51 °C 30x",
    __1: "We are now using ELAV inner (NI_100 (F) and NI_84(R) instead F+R)",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "EXO",
    initialDenaturation: "37°C, 15 min",
    denaturation: "80°C, 15 min",
    annealing: "",
    extension: "",
    numberCycles: "",
    finalExtension: "",
    end: "8°C for ever",
    pcrProductSize: "",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "ELAV OUT",
    initialDenaturation: "96°C, 10 min",
    denaturation: "94 °C, 30 s",
    annealing: "50 °C, 30 s",
    extension: "72 °C, 1:30 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4°C for ever",
    pcrProductSize: "",
    note: "ELAV vnějí primery, 1. PCR s DNA",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "ELAV IN",
    initialDenaturation: "96°C, 10 min",
    denaturation: "94 °C, 30 s",
    annealing: "52 °C, 30 s",
    extension: "72 °C, 1:30 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4°C for ever",
    pcrProductSize: "",
    note: "ELAV vnitřní primery, 2. PCR s PCR produktem z ELAV OUT nebo jako jednokroková PCR (pro kvalitní vzorky)",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "ELAV Rodrigo 50",
    initialDenaturation: "96°C, 10 min",
    denaturation: "94 °C, 30 s",
    annealing: "50 °C, 45 s",
    extension: "72 °C, 1 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4°C for ever",
    pcrProductSize: "",
    note: "původní protokol pro ELAV",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "",
    initialDenaturation: "",
    denaturation: "",
    annealing: "",
    extension: "",
    numberCycles: "",
    finalExtension: "",
    end: "",
    pcrProductSize: "",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "",
    initialDenaturation: "",
    denaturation: "",
    annealing: "",
    extension: "",
    numberCycles: "",
    finalExtension: "",
    end: "",
    pcrProductSize: "",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "",
    initialDenaturation: "",
    denaturation: "",
    annealing: "",
    extension: "",
    numberCycles: "",
    finalExtension: "",
    end: "",
    pcrProductSize: "",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
  {
    name: "",
    initialDenaturation: "",
    denaturation: "",
    annealing: "",
    extension: "",
    numberCycles: "",
    finalExtension: "",
    end: "",
    pcrProductSize: "",
    note: "",
    __1: "",
    __2: "",
    __3: "",
    __4: "",
    __5: "",
    __6: "",
    __7: "",
    __8: "",
    __9: "",
    __10: "",
    __11: "",
    __12: "",
    __13: "",
    __14: "",
    __15: "",
  },
];
