export const backup = [
  {
    name: "UNIVGRAD",
    initialDenaturation: "96 °C, 10 min",
    denaturation: "94  °C, 30 s",
    annealing: "45-52 °C, 30 s",
    extension: "72 °C, 1 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4 °C for ever",
    pcrProductSize: "",
    note: "",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "CYTCO45",
    initialDenaturation: "",
    denaturation: "",
    annealing: "45 °C",
    extension: "",
    numberCycles: "40 x",
    finalExtension: "",
    end: "",
    pcrProductSize: "CytB (400 bp)",
    note: "",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "CO1-46",
    initialDenaturation: "",
    denaturation: "",
    annealing: "46 °C",
    extension: "",
    numberCycles: "40 x",
    finalExtension: "",
    end: "",
    pcrProductSize: "COI (700 bp)",
    note: "",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "16S-50",
    initialDenaturation: "",
    denaturation: "",
    annealing: "50 °C",
    extension: "",
    numberCycles: "40 x",
    finalExtension: "",
    end: "",
    pcrProductSize: "16S (400 bp)",
    note: "",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "ITS-52",
    initialDenaturation: "",
    denaturation: "",
    annealing: "52 °C",
    extension: "",
    numberCycles: "40 x",
    finalExtension: "",
    end: "",
    pcrProductSize: "ITS1 (700 nt), ITS2 (900 nt)",
    note: "",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "ELAV",
    initialDenaturation: "96 °C, 10 min",
    denaturation: "94  °C, 30 s",
    annealing: "50 °C",
    extension: "72 °C, 1 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4 °C for ever",
    pcrProductSize: "",
    note: "sometimes: 54 °C 10x, then 51 °C 30x",
    FIELD11: "",
    FIELD12:
      "We are now using ELAV inner (NI_100 (F) and NI_84(R) instead F+R)",
  },
  {
    name: "EXO",
    initialDenaturation: "",
    denaturation: "",
    annealing: "",
    extension: "",
    numberCycles: "",
    finalExtension: "",
    end: "",
    pcrProductSize: "",
    note: "",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "ELAV OUT",
    initialDenaturation: "96 °C, 10 min",
    denaturation: "94  °C, 30 s",
    annealing: "50 °C, 30 s",
    extension: "72 °C, 1:30 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4 °C for ever",
    pcrProductSize: "",
    note: "ELAV vnější primery, 1. PCR s DNA",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "ELAV IN",
    initialDenaturation: "96 °C, 10 min",
    denaturation: "94  °C, 30 s",
    annealing: "52 °C, 30 s",
    extension: "72 °C, 1:30 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4 °C for ever",
    pcrProductSize: "",
    note: "ELAV vnitřní primery, 2. PCR s PCR produktem z ELAV OUT nebo jako jednokroková PCR (pro kvalitní vzorky)",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "ELAV Rodrigo 50",
    initialDenaturation: "96 °C, 10 min",
    denaturation: "94  °C, 30 s",
    annealing: "50 °C, 45 s",
    extension: "72 °C, 1 min",
    numberCycles: "40 x",
    finalExtension: "72 °C, 10 min",
    end: "4 °C for ever",
    pcrProductSize: "",
    note: "původní protokol pro ELAV",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "COI_VitG",
    initialDenaturation: "95 °C, 2 min",
    denaturation: "95 °C, 1 min",
    annealing: "44-49 °C, 1 min",
    extension: "72 °C, 1 min",
    numberCycles: "35 x",
    finalExtension: "72 °C, 10 min",
    end: "4 °C for ever",
    pcrProductSize: "",
    note: "pro test COI primerů na Vitrinu, leden 2023",
    FIELD11: "",
    FIELD12: "",
  },
  {
    name: "SUCC-56",
    initialDenaturation: "94 °C, 3 min",
    denaturation: "94 °C, 30 s",
    annealing: "56 °C, 30 s",
    extension: "72 °C, 1 min",
    numberCycles: "40 x",
    finalExtension: "72°C, 7 min",
    end: "4 °C for ever",
    pcrProductSize: "",
    note: "pro test Succinea, Oxyloma ITS primerů, leden 2023, teplota dle publikace 56, zkoušeno s 54 a obvykle více proužků",
    FIELD11: "",
    FIELD12: "",
  },
];
