export const backup = [
  {
    name: "L1490-Alb (F)",
    marker: "COI",
    specificity: "Arianta / Euconulus / Gyraulus",
    sequence: "actcaacgaatcataaagatattgg",
    author: "Gittenberger, Piel & Groenenberg (2004)",
    anneal: "45-48°C",
    lengthPCR: 800,
    work: "yes",
    noteOnUse:
      "used for Euconulus (45°C anneal, program EuconCOI-II 45), Gyraulus (46°C anneal, UNIVGRAD 3rd row), Vertigo, Arianta (48°C anneal)",
    box: "1",
  },
  {
    name: "BCO (R)",
    marker: "COI",
    specificity: "Arianta / Euconulus / Gyraulus",
    sequence: "gtatcggctgtaaaataagc",
    author: "Haase et al. (2003)",
    anneal: "45-48°C",
    lengthPCR: 800,
    work: "yes",
    noteOnUse:
      "used for Euconulus (45°C anneal, program EuconCOI-II 45), Gyraulus (46°C anneal, UNIVGRAD 3rd row), Vertigo, Arianta (48°C anneal)",
    box: "1",
  },
  {
    name: "COII-F",
    marker: "COII",
    specificity: "Euconulus",
    sequence: "AAATAATGCTATTTCATGAYCAYGC",
    author: "Hugall et al. (2002)",
    anneal: "45°C",
    lengthPCR: 550,
    work: "yes",
    noteOnUse:
      "used for Euconulus (45°C anneal, program EuconCOI-II 45 / UNIVGRAD left row)",
    box: "1",
  },
  {
    name: "COII-R",
    marker: "COII",
    specificity: "Euconulus",
    sequence: "GCTCCGCAAATCTCTGARCAYTG",
    author: "Hugall et al. (2002)",
    anneal: "45°C",
    lengthPCR: 550,
    work: "yes",
    noteOnUse:
      "used for Euconulus (45°C anneal, program EuconCOI-II 45 / UNIVGRAD left row)",
    box: "1",
  },
  {
    name: "CytB-F",
    marker: "CytB",
    specificity: "Vertigo / Pupilla",
    sequence: "YWYTRCCTTGGRGGRCARATATC",
    author: "Author design, Nekola",
    anneal: "47°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "",
    box: "1",
  },
  {
    name: "CytB-R",
    marker: "CytB",
    specificity: "Vertigo / Pupilla",
    sequence: "GCRWAYARAAARTAYCAYTCWGG",
    author: "Author design, Nekola",
    anneal: "47°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "",
    box: "1",
  },
  {
    name: "16S-F",
    marker: "16S",
    specificity: "universal",
    sequence: "GCGCTGTTTATCAAAAACAT",
    author: "Palumbi et al. (2002)",
    anneal: "52°C",
    lengthPCR: 400,
    work: "yes",
    noteOnUse:
      "used for Euconulus (Eucon ITS-16S / UNIVGRAD right row), other Holarctic genera",
    box: "1",
  },
  {
    name: "16S-R",
    marker: "16S",
    specificity: "universal",
    sequence: "CCGGTYTGAACTCAGATCAYGT",
    author: "Palumbi et al. (2002)",
    anneal: "52°C",
    lengthPCR: 400,
    work: "yes",
    noteOnUse:
      "used for Euconulus (Eucon ITS-16S / UNIVGRAD right row), other Holarctic genera",
    box: "1",
  },
  {
    name: "ITS1-F",
    marker: "ITS1",
    specificity: "universal",
    sequence: "TAACAAGGTTTCCGTATGTGAA",
    author: "Armbruster & Bernhard (2000)",
    anneal: "52°C",
    lengthPCR: 700,
    work: "yes",
    noteOnUse:
      "used for Euconulus (Eucon ITS-16S / UNIVGRAD right row), other Holarctic genera",
    box: "1",
  },
  {
    name: "ITS1-R",
    marker: "ITS1",
    specificity: "universal",
    sequence: "TCACATTAATTCTCGCAGCTAG",
    author: "Author design, Nekola",
    anneal: "52°C",
    lengthPCR: 700,
    work: "yes",
    noteOnUse:
      "used for Euconulus (Eucon ITS-16S / UNIVGRAD right row), other Holarctic genera",
    box: "1",
  },
  {
    name: "LSU-1 (F)",
    marker: "ITS2",
    specificity: "universal",
    sequence: "CTAGCTGCGAGAATTAATGTGA",
    author: "Wade & Mordan (2000)",
    anneal: "52°C",
    lengthPCR: 900,
    work: "yes",
    noteOnUse:
      "used for Euconulus (Eucon ITS-16S / UNIVGRAD right row), other Holarctic genera",
    box: "1",
  },
  {
    name: "LSU3rm (R)",
    marker: "ITS2",
    specificity: "universal",
    sequence: "GGTTTCACGTACTCTTGAAC",
    author: "Author design, Nekola",
    anneal: "52°C",
    lengthPCR: 900,
    work: "yes",
    noteOnUse:
      "used for Euconulus (Eucon ITS-16S / UNIVGRAD right row), other Holarctic genera",
    box: "1",
  },
  {
    name: "LCO1490 (5')",
    marker: "COI",
    specificity: "Pyramidula / Gyraulus / universal mollusc",
    sequence: "GGTCAACAAATCATAAAGATATTGG",
    author: "Folmer et al. (1994)",
    anneal: "45°C",
    lengthPCR: 700,
    work: "yes",
    noteOnUse: "used for Pyramidula (UNIVGRAD left row)",
    box: "1",
  },
  {
    name: "HCO2198 (3')",
    marker: "COI",
    specificity: "Pyramidula / Gyraulus / universal mollusc",
    sequence: "TAAACTTCAGGGTGACCAAAAAATCA",
    author: "Folmer et al. (1994)",
    anneal: "45°C",
    lengthPCR: 700,
    work: "yes",
    noteOnUse: "used for Pyramidula (UNIVGRAD left row)",
    box: "1",
  },
  {
    name: "LSU-1 (5’)",
    marker: "5.8S-ITS2",
    specificity: "Pyramidula",
    sequence: "CTAGCTGCGAGAATTAATGTGA",
    author: "Wade et al. (2006)",
    anneal: "50°C",
    lengthPCR: 900,
    work: "yes, but replaced",
    noteOnUse: "replaced by universal ITS1, ITS2",
    box: "1",
  },
  {
    name: "LSU-3 (3’)",
    marker: "5.8S-ITS2",
    specificity: "Pyramidula",
    sequence: "ACTTTCCCTCACGGTACTTG",
    author: "Wade et al. (2006)",
    anneal: "50°C",
    lengthPCR: 900,
    work: "yes, but replaced",
    noteOnUse: "replaced by universal ITS1, ITS2",
    box: "1",
  },
  {
    name: "LSU-2",
    marker: "28S",
    specificity: "",
    sequence: "GGGTTGTTTGGGAATGCAGC",
    author: "Wade et al. (2006)",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "",
    box: "",
  },
  {
    name: "LSU-2mod (5’)",
    marker: "28S",
    specificity: "Pyramidula",
    sequence: "TCTCAGGAGTCGGGTTGTTT",
    author: "Razkin et al. (2015)",
    anneal: "50°C",
    lengthPCR: 600,
    work: "yes, but replaced",
    noteOnUse: "replaced by universal ITS1, ITS2",
    box: "1",
  },
  {
    name: "LSU-5 (3’)=LSU 4 R",
    marker: "28S",
    specificity: "Pyramidula",
    sequence: "GTTAGACTCCTTGGTCCGTG",
    author: "Wade et al. (2006)",
    anneal: "50°C",
    lengthPCR: 600,
    work: "yes, but replaced",
    noteOnUse: "replaced by universal ITS1, ITS2",
    box: "1",
  },
  {
    name: "16s-109 (5’)",
    marker: "16S",
    specificity: "Pyramidula",
    sequence: "CCTTGACTGTGCAAAGGTAGC",
    author: "Ketmaier et al. (2006)",
    anneal: "55 °C",
    lengthPCR: 300,
    work: "no",
    noteOnUse: "tried for Pyramidula, not used",
    box: "1",
  },
  {
    name: "16s-421 (3’)",
    marker: "16S",
    specificity: "Pyramidula",
    sequence: "TAGGCCCTAATCCAACATCG",
    author: "Ketmaier et al. (2006)",
    anneal: "55 °C",
    lengthPCR: 300,
    work: "no",
    noteOnUse: "tried for Pyramidula, not used",
    box: "1",
  },
  {
    name: "16sar-L",
    marker: "16S",
    specificity: "Gyraulus",
    sequence: "CGCCTGTTTATCAAAAACAT",
    author: "Palumbi et al. (1996)",
    anneal: "50°C",
    lengthPCR: null,
    work: "no",
    noteOnUse: "tried for Gyraulus, not used",
    box: "1",
  },
  {
    name: "16sbr-H",
    marker: "16S",
    specificity: "Gyraulus",
    sequence: "CCGGTCTGAACTCAGATCACGT",
    author: "Palumbi et al. (1996)",
    anneal: "50°C",
    lengthPCR: null,
    work: "no",
    noteOnUse: "tried for Gyraulus, not used",
    box: "1",
  },
  {
    name: "UCYTB151F",
    marker: "CytB",
    specificity: "Gyraulus / universal",
    sequence: "TGTGGRGCNACYGTWATYACTAA",
    author: "Merritt et al. (1998)",
    anneal: "48°C",
    lengthPCR: null,
    work: "no",
    noteOnUse: "replaced by specific CytB",
    box: "1",
  },
  {
    name: "UCYTB270R",
    marker: "CytB",
    specificity: "Gyraulus / universal",
    sequence: "AANAGGAARTAYCAYTCNGGYTG",
    author: "Merritt et al. (1998)",
    anneal: "48°C",
    lengthPCR: null,
    work: "no",
    noteOnUse: "replaced by specific CytB",
    box: "1",
  },
  {
    name: "LT1",
    marker: "ITS2",
    specificity: "Gyraulus",
    sequence: "TCGTCTGTGTGAGGGTCG",
    author: "Bargues et al. (2001)",
    anneal: "50°C",
    lengthPCR: null,
    work: "no",
    noteOnUse: "replaced by universal ITS1, ITS2",
    box: "1",
  },
  {
    name: "ITS2-RIXO",
    marker: "ITS2",
    specificity: "Gyraulus",
    sequence: "TTCTATGCTTAAATTCAGGGG",
    author: "Almeyda-Artigas et al. (2000)",
    anneal: "50°C",
    lengthPCR: null,
    work: "no",
    noteOnUse: "replaced by universal ITS1, ITS2",
    box: "1",
  },
  {
    name: "CytB_F_Pup",
    marker: "CytB",
    specificity: "Pupilla / Vertigo",
    sequence: "TGAGGTGCAACAGTNATTAC",
    author: "Author design, Nekola",
    anneal: "45°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse: "specific for Pupilla (program CytBCO)",
    box: "1",
  },
  {
    name: "CytB_R_Pup",
    marker: "CytB",
    specificity: "Pupilla / Vertigo",
    sequence: "GCAAATAAAAAGTATCACTCTGG",
    author: "Author design, Nekola",
    anneal: "45°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse: "specific for Pupilla (program CytBCO)",
    box: "1",
  },
  {
    name: "CytB_F_Gyr",
    marker: "CytB",
    specificity: "Gyraulus",
    sequence: "GTKTTACCATGAGGRCAAATATC",
    author: "Author design, Horsáková",
    anneal: "47°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse:
      "specific design, work for Gyraulus (45°C anneal), tested also for Columella, Zoogenetes (47°C anneal) (program CytBCO / UNIVGRAD 3rd row)",
    box: "1",
  },
  {
    name: "CytB_R_Gyr",
    marker: "CytB",
    specificity: "Gyraulus",
    sequence: "GCAAAYAAAAAATATCATTCTGG",
    author: "Author design, Horsáková",
    anneal: "47°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse:
      "specific design, work for Gyraulus (45°C anneal), tested also for Columella, Zoogenetes (47°C anneal) (program CytBCO / UNIVGRAD 3rd row)",
    box: "1",
  },
  {
    name: "COI_F_Gyr",
    marker: "COI",
    specificity: "Gyraulus",
    sequence: "TCAACAAAYCAYAAAGATATTGG",
    author: "Author design, Horsáková",
    anneal: "45°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse: "",
    box: "1",
  },
  {
    name: "COI_R_Gyr",
    marker: "COI",
    specificity: "Gyraulus",
    sequence: "CTTCWGGATGACCAAAAAAYC",
    author: "Author design, Horsáková",
    anneal: "45°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse: "",
    box: "1",
  },
  {
    name: "CO1f-Zoo",
    marker: "COI",
    specificity: "universal",
    sequence: "TCTACTAATCATAAAGATATTGG",
    author: "Jeff's design",
    anneal: "",
    lengthPCR: null,
    work: "?",
    noteOnUse: "designed based on genomics",
    box: "1",
  },
  {
    name: "CO1r-Zoo",
    marker: "COI",
    specificity: "universal",
    sequence: "CTTCAGGATGTCCAAAAAATCA",
    author: "Jeff's design",
    anneal: "",
    lengthPCR: null,
    work: "?",
    noteOnUse: "designed based on genomics",
    box: "1",
  },
  {
    name: "COIuni_F",
    marker: "COI",
    specificity: "universal",
    sequence: "TCIACIAAYCAYAARGAYATYGG",
    author: "Jeff's Albuquerque design",
    anneal: "45°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program CytBCO)",
    box: "1",
  },
  {
    name: "COIuni_R",
    marker: "COI",
    specificity: "universal",
    sequence: "GTRATISSICCIGCHARNACNGG",
    author: "Jeff's Albuquerque design",
    anneal: "45°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program CytBCO)",
    box: "1",
  },
  {
    name: "COIIuni_F",
    marker: "COII",
    specificity: "universal",
    sequence: "GARATRIWHYTITTYCAYGAYCA",
    author: "Jeff's Albuquerque design",
    anneal: "45°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program CytBCO)",
    box: "1",
  },
  {
    name: "COIIuni_R",
    marker: "COII",
    specificity: "universal",
    sequence: "CCRCARATYTCISWRCAYTGNCC",
    author: "Jeff's Albuquerque design",
    anneal: "45°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program CytBCO)",
    box: "1",
  },
  {
    name: "COIIIuni_F",
    marker: "COIII",
    specificity: "universal",
    sequence: "CGIGARDSIWCHTWYCARGG",
    author: "Jeff's Albuquerque design",
    anneal: "45°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program CytBCO)",
    box: "1",
  },
  {
    name: "COIIIuni_R",
    marker: "COIII",
    specificity: "universal",
    sequence: "ACRAARTGYCARTAYCADGC",
    author: "Jeff's Albuquerque design",
    anneal: "45°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program CytBCO)",
    box: "1",
  },
  {
    name: "CytBuni_F",
    marker: "CytB",
    specificity: "universal",
    sequence: "TIYTICCITGRGGNCARATRTC",
    author: "Jeff's Albuquerque design",
    anneal: "47°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program UNIVGRAD 3rd row)",
    box: "1",
  },
  {
    name: "CytBuni_R",
    marker: "CytB",
    specificity: "universal",
    sequence: "GCIRAAIARRAARTAYCAYTCNGG",
    author: "Jeff's Albuquerque design",
    anneal: "47°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program UNIVGRAD 3rd row)",
    box: "1",
  },
  {
    name: "16Suni_F",
    marker: "16S",
    specificity: "universal",
    sequence: "NCTGKTTAHCAAAAACATAR",
    author: "Jeff's Albuquerque design",
    anneal: "50°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program UNIVGRAD 8-9th row)",
    box: "1",
  },
  {
    name: "16Suni_R",
    marker: "16S",
    specificity: "universal",
    sequence: "CRCCGGTCTGAACTCAGATCA",
    author: "Jeff's Albuquerque design",
    anneal: "50°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program UNIVGRAD 8-9th row)",
    box: "1",
  },
  {
    name: "12Suni_F",
    marker: "12S",
    specificity: "universal",
    sequence: "GTGCCAGCARHYGCGGTYANAC",
    author: "Jeff's Albuquerque design",
    anneal: "50°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program UNIVGRAD 9-10th row)",
    box: "1",
  },
  {
    name: "12Suni_R",
    marker: "12S",
    specificity: "universal",
    sequence: "AGARYGACGGGCGATTTGTRC",
    author: "Jeff's Albuquerque design",
    anneal: "50°C",
    lengthPCR: null,
    work: "?",
    noteOnUse: "Jeff's universal design (program UNIVGRAD 9-10th row)",
    box: "1",
  },
  {
    name: "Col-CytBfe",
    marker: "CytB",
    specificity: "Columella",
    sequence: "GGACGAGGTCTTTATTATAGTTC",
    author: "",
    anneal: "57°C",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Col-CytBf",
    marker: "CytB",
    specificity: "Columella",
    sequence: "TGAGGTGCAACTGTTATTAC",
    author: "",
    anneal: "57°C",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Col-CytBr",
    marker: "CytB",
    specificity: "Columella",
    sequence: "GCAAAAAGAAAATATCATTCAGG",
    author: "",
    anneal: "57°C",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Nes_CytBfe",
    marker: "CytB",
    specificity: "Nesovitrea",
    sequence: "GGACGTGGAATTTATTATCAAAG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "lyof",
  },
  {
    name: "Nes_CytBf",
    marker: "CytB",
    specificity: "Nesovitrea",
    sequence: "TGAGGAGCAACAGTTATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "lyof",
  },
  {
    name: "Nes_CytBr",
    marker: "CytB",
    specificity: "Nesovitrea",
    sequence: "GCG AAT AAA AAA TAT CAC TCA GG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse:
      "Don´t use (does not work for binneyana), use NesUni_cytBr designed based on genomics",
    box: "lyof",
  },
  {
    name: "NesUni_cytBr",
    marker: "cytB",
    specificity: "Nesovitrea universal",
    sequence: "GCR AAT AAR AAA TAT CAC TCR GG",
    author: "Marketa",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse:
      "Use for all Nesovitrea, designed based on long range PCR specifically for Nes. binneyana. 3 SNVs found, new R primer contains 3 degenerated bases (R=A+G)",
    box: "",
  },
  {
    name: "ELAV-F",
    marker: "ELAV",
    specificity: "universal",
    sequence: "GAATACTTTATGATCAAACCAC",
    author: "",
    anneal: "54 °C 10x, then 51 °C 30x",
    lengthPCR: null,
    work: "yes, but suboptimal",
    noteOnUse: "designed based on genomics (Coen)",
    box: "",
    FIELD11: "",
    FIELD12: "",
    FIELD13:
      "Only for special cases: for genera that cannot be amplified by NI_84 and NI_100. ELAV F+R are original primers, NI_84 and 100 are optimized, usually higher sensitivity.",
  },
  {
    name: "ELAV-R",
    marker: "ELAV",
    specificity: "universal",
    sequence: "GGCAGCCCACTTACATACAAG",
    author: "",
    anneal: "54 °C 10x, then 51 °C 30x",
    lengthPCR: null,
    work: "yes, but suboptimal",
    noteOnUse: "designed based on genomics (Coen)",
    box: "",
    FIELD11: "",
    FIELD12: "",
    FIELD13:
      "Only for special cases: for genera that cannot be amplified by NI_84 and NI_100. ELAV F+R are original primers, NI_84 and 100 are optimized, usually higher sensitivity.",
  },
  {
    name: "ELAVF_NO_88",
    marker: "ELAV",
    specificity: "universal",
    sequence: "GCTAACTTATATATTAGTGGCTTGC",
    author: "",
    anneal: "50°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse: "designed based on genomics (Coen)",
    box: "",
    FIELD11: "",
    FIELD12: "",
    FIELD13: "nested outer primers",
  },
  {
    name: "ELAVR_NO_93",
    marker: "ELAV",
    specificity: "universal",
    sequence: "GTGTGTGTATCATAAAGAATTCG",
    author: "",
    anneal: "50°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse: "designed based on genomics (Coen)",
    box: "",
    FIELD11: "",
    FIELD12: "",
    FIELD13: "nested outer primers",
  },
  {
    name: "ELAVF_NI_100",
    marker: "ELAV",
    specificity: "universal",
    sequence: "ATGACACAGTTGGACTTGGAG",
    author: "",
    anneal: "52°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse: "designed based on genomics (Coen)",
    box: "",
    FIELD11: "",
    FIELD12: "",
    FIELD13: "nested inner primers or single-step PCR",
  },
  {
    name: "ELAVR_NI_84",
    marker: "ELAV",
    specificity: "universal",
    sequence: "GAGAACAACTTCTCCAAATCCT",
    author: "",
    anneal: "52°C",
    lengthPCR: null,
    work: "yes",
    noteOnUse: "designed based on genomics (Coen)",
    box: "",
    FIELD11: "",
    FIELD12: "",
    FIELD13: "nested inner primers or single-step PCR",
  },
  {
    name: "Val-CytBfe",
    marker: "CytB",
    specificity: "Vallonia",
    sequence: "GGACGAGGTCTTTACTACCAAAG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Val-CytBf",
    marker: "CytB",
    specificity: "Vallonia",
    sequence: "TGAGGGGCTACAGTAATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Val-CytBr",
    marker: "CytB",
    specificity: "Vallonia",
    sequence: "GCAAAAAGAAAATATCATTCTGG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Zoo-CytBfe",
    marker: "CytB",
    specificity: "Zoogenetes",
    sequence: "GGTCGGGGKCTTTATTACCAAAG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Zoo-CytBf",
    marker: "CytB",
    specificity: "Zoogenetes",
    sequence: "TGAGGAGCTACTGTAATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Zoo-CytBr",
    marker: "CytB",
    specificity: "Zoogenetes",
    sequence: "GCGAATAAAAAGTATCACTCAGG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Pla-CytBfe",
    marker: "CytB",
    specificity: "Planogyra",
    sequence: "GGACGAGGACTTTATTACCAAAG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Pla-CytBf",
    marker: "CytB",
    specificity: "Planogyra",
    sequence: "TGAGGAGCTACAGTTATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Pla-CytBr",
    marker: "CytB",
    specificity: "Planogyra",
    sequence: "GCGAACAAGAAATATCATTCTGG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Coc-CytBfe",
    marker: "CytB",
    specificity: "Cochlicopa",
    sequence: "GGACGAGGTTTATACTATCAGAG",
    author: "",
    anneal: "57 °C",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Coc-CytBf",
    marker: "CytB",
    specificity: "Cochlicopa",
    sequence: "TGGGGAGCTACAGTAATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "no - amplify 2 bands (very probably)",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Coc-CytBr",
    marker: "CytB",
    specificity: "Cochlicopa",
    sequence: "GCAAATAAAAAATATCATTCAGG",
    author: "",
    anneal: "57 °C",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Euc-CytBfe",
    marker: "CytB",
    specificity: "Euconulus",
    sequence: "GGACGTGGACTTTATTATCAAAG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Euc-CytBf",
    marker: "CytB",
    specificity: "Euconulus",
    sequence: "TGAGGTGCTACTGTAATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Euc-CytBr",
    marker: "CytB",
    specificity: "Euconulus",
    sequence: "GCAAATAAAAAATATCATTCTGG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Zon-CytBfe",
    marker: "CytB",
    specificity: "Zonitoides",
    sequence: "GGACGTGGAATTTACTATCAAAG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Zon-CytBf",
    marker: "CytB",
    specificity: "Zonitoides",
    sequence: "TGGGCGGCAACGGTAATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Zon-CytBr",
    marker: "CytB",
    specificity: "Zonitoides",
    sequence: "GCAAACAAAAAGTATCATTCAGG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Pun-CytBfe",
    marker: "CytB",
    specificity: "Punctum",
    sequence: "gggcggggcttatattatcaaag",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Pun-CytBf",
    marker: "CytB",
    specificity: "Punctum",
    sequence: "tggggggctactgtaattac",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Pun-CytBr",
    marker: "CytB",
    specificity: "Punctum",
    sequence: "gcaaataagaaatatcattcagg",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Dis-CytBfe",
    marker: "CytB",
    specificity: "Discus",
    sequence: "GGTCGAGGACTTTACTATCAAAG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Dis-CytBf",
    marker: "CytB",
    specificity: "Discus",
    sequence: "TGGGGGGCCACAGTTATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Dis-CytBr",
    marker: "CytB",
    specificity: "Discus",
    sequence: "GCAAATAAAAAGTATCACTCGGG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Oxy-CytBfe",
    marker: "CytB",
    specificity: "Oxyloma",
    sequence: "GGTCGGGGGTTATACTATCAAAG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Oxy-CytBf",
    marker: "CytB",
    specificity: "Oxyloma",
    sequence: "TGAGGTGCCACAGTTATTAC",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Oxy-CytBr",
    marker: "CytB",
    specificity: "Oxyloma",
    sequence: "GCAAATAAAAAATATCACTCAGG",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Suc-CytBfe",
    marker: "CytB",
    specificity: "Succinea",
    sequence: "ggacgaggtttatattatcagag",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Suc-CytBf",
    marker: "CytB",
    specificity: "Succinea",
    sequence: "tgaggtgctacagttattac",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "Suc-CytBr",
    marker: "CytB",
    specificity: "Succinea",
    sequence: "gcgaataaaaagtatcattcagg",
    author: "",
    anneal: "",
    lengthPCR: null,
    work: "",
    noteOnUse: "designed based on genomics",
    box: "",
  },
  {
    name: "FCOI_L1490-Alb",
    marker: "COI",
    specificity: "Vitrina",
    sequence: "ACTCAACGAATCATAAAGATATTGG",
    author: "",
    anneal: "45°C",
    lengthPCR: null,
    work: "too universal, multiple peaks",
    noteOnUse:
      "see Pfarrer et al. in prep (2023), will be tested for Vitrea - same as COIF(Pyr)",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "ROCI_H2198-Alb",
    marker: "COI",
    specificity: "Vitrina",
    sequence: "TATACTTCAGGATGACCAAAAAATCA",
    author: "",
    anneal: "45°C",
    lengthPCR: null,
    work: "too universal, multiple peaks",
    noteOnUse: "see Pfarrer et al. in prep (2023), will be tested for Vitrea",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "VitCO1_11F",
    marker: "COI",
    specificity: "Vitrina",
    sequence: "ACAAATCATAAAGATATTGGTACA",
    author: "",
    anneal: "49°C",
    lengthPCR: null,
    work: "work well with 683",
    noteOnUse: "see Pfarrer et al. in prep (2023), will be tested for Vitrea",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "VitCO1_415R",
    marker: "COI",
    specificity: "Vitrina",
    sequence: "CAAATCTACTGAAGCACCAG",
    author: "",
    anneal: "49°C",
    lengthPCR: null,
    work: "seem to work but better to use 11+683",
    noteOnUse: "see Pfarrer et al. in prep (2023), will be tested for Vitrea",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "VitCO1_250F",
    marker: "COI",
    specificity: "Vitrina",
    sequence: "TGATATAAGATTTCCTCGTA",
    author: "",
    anneal: "44°C",
    lengthPCR: null,
    work: "seem to work but better to use 11+683",
    noteOnUse: "see Pfarrer et al. in prep (2023), will be tested for Vitrea",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "VitCO1_683R",
    marker: "COI",
    specificity: "Vitrina",
    sequence: "AAAGATGTTGATATAAAATAGG",
    author: "",
    anneal: "44°C",
    lengthPCR: null,
    work: "work well with 11",
    noteOnUse: "see Pfarrer et al. in prep (2023), will be tested for Vitrea",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "ITS_F_Oxy",
    marker: "ITS",
    specificity: "Oxyloma",
    sequence: "TGCGGAAGGATCATTATCGT",
    author: "",
    anneal: "56°C",
    lengthPCR: null,
    work: "currently in use for Succinea and Oxyloma",
    noteOnUse: "see Culver et al. 2013",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "ITS_R_Oxy",
    marker: "ITS",
    specificity: "Oxyloma",
    sequence: "CGCTTAAAGTTGTCAGATGA",
    author: "",
    anneal: "56°C",
    lengthPCR: null,
    work: "currently in use for Succinea and Oxyloma",
    noteOnUse: "see Culver et al. 2013",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "ITS1_F_Suc",
    marker: "ITS1",
    specificity: "Succinea",
    sequence: "TCGGATTGGTCTCGGTCTG",
    author: "",
    anneal: "57°C",
    lengthPCR: null,
    work: "multiple bands at 54°C anneal",
    noteOnUse: "see Prokhorova et al. 2020",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "ITS1_R_Suc",
    marker: "ITS1",
    specificity: "Succinea",
    sequence: "GCGTTCAAGATGTCGATGTTC",
    author: "",
    anneal: "57°C",
    lengthPCR: null,
    work: "multiple bands at 54°C anneal",
    noteOnUse: "see Prokhorova et al. 2020",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "ITS2_F_Suc",
    marker: "ITS2",
    specificity: "Succinea",
    sequence: "TTGCAGAACACATTGAACATCG",
    author: "",
    anneal: "57°C",
    lengthPCR: null,
    work: "multiple bands at 54°C anneal",
    noteOnUse: "see Prokhorova et al. 2020",
    box: "PRIMERS Suc+Vit",
  },
  {
    name: "ITS2_R_Suc",
    marker: "ITS2",
    specificity: "Succinea",
    sequence: "GGAGTTTACCACCCGCTTTG",
    author: "",
    anneal: "57°C",
    lengthPCR: null,
    work: "multiple bands at 54°C anneal",
    noteOnUse: "see Prokhorova et al. 2020",
    box: "PRIMERS Suc+Vit",
  },
];
