export const backup = [
  { box: "E1", storageSite: "-80°C (1S24)" },
  { box: "OP1", storageSite: "extraction room -20" },
  { box: "AG1", storageSite: "extraction room -20" },
  { box: "G2", storageSite: "-80°C (1S24)" },
  { box: "UCE1", storageSite: "extraction room -20" },
  { box: "AG2", storageSite: "extraction room -20" },
  { box: "HD3", storageSite: "extraction room -20" },
  { box: "", storageSite: "extraction room -20" },
  { box: "Eva L.", storageSite: "extraction room -20" },
  { box: "E2", storageSite: "-80°C (1S24)" },
  { box: "UCE2", storageSite: "extraction room -20" },
  { box: "Nekola", storageSite: "extraction room -20" },
  { box: "G1", storageSite: "-80°C (Freezer room, D31)" },
  { box: "G3", storageSite: "extraction room -20" },
  { box: "VYŘAZENO", storageSite: "" },
  { box: "G4", storageSite: "extraction room -20, new freezer" },
  { box: "HD1", storageSite: "-80°C (1S24)" },
  { box: "HD2", storageSite: "-80°C (1S24)" },
  { box: "NE1", storageSite: "extraction room -20" },
  { box: "HD5", storageSite: "-80°C (1S24)" },
  { box: "DF1", storageSite: "-80°C (1S24)" },
  { box: "HD7", storageSite: "extraction room -20" },
  { box: "NE2", storageSite: "extraction room -20" },
  { box: "NE3", storageSite: "extraction room -20" },
  { box: "green rack", storageSite: "in the fridge" },
  { box: "P1", storageSite: "extraction room -20" },
  { box: "HD6", storageSite: "extraction room -20" },
  { box: "Jeff Haplotrema extractions", storageSite: "-80°C (1S24)" },
  { box: "P2", storageSite: "-80°C (1S24)" },
  { box: "S1", storageSite: "-80°C (1S24)" },
];
